### ISSUE TITLE
Complex action criteria does not work

### ISSUE THREAD

**Issue by dimw** [automate-website/jwebrobot#1]
Loading of the following scenario fails:

``` yaml
name: Action with complex criteria
steps:
    - open:
        url: 'www.example.com'
```
